# Generated by Django 3.1.4 on 2020-12-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201219_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='url_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Url Code'),
        ),
    ]
