# Generated by Django 3.1.4 on 2020-12-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201219_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='shortened_url',
        ),
    ]
